name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up Julia
        uses: julia-actions/setup-julia@v1
        with:
          version: '1.9'

      - name: Instantiate Project Dependencies
        run: julia --project=. -e 'using Pkg; Pkg.instantiate()'

      - name: Run Tests and Save Results
        run: |
          # Run the tests, saving output to a log file
          julia --project=. -e 'using Pkg; Pkg.test()' 2>&1 | tee test_results.log

      - name: Upload Test Results Artifact
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: test-results
          path: test_results.log

      - name: Build Package
        run: |
          # Build the package (for example, running Pkg.build())
          julia --project=. -e 'using Pkg; Pkg.build()'
          # Create an artifact; here we zip the repository as an example.
          # Adjust the contents and destination as needed for your package.
          zip -r package_artifact.zip .

      - name: Upload Built Package Artifact
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: built-package
          path: package_artifact.zip
